server:
  port: 8080
spring:
  datasource:
    name: test
    #url: jdbc:oracle:thin:@192.168.1.199:1521:jk
    #username: jkrm
    #password: SHjkrm!23$
    url: jdbc:oracle:thin:@10.218.94.34:1521:PDB_JK
    username: jk
    password: Hndb1#2
    # ??druid???
    #        type: com.alibaba.druid.pool.DruidDataSource
    #        driver-class-name: oracle.jdbc.OracleDriver
    #        filters: stat
    #        maxActive: 20
    #        initialSize: 1
    #        maxWait: 60000
    #        minIdle: 1
    #        timeBetweenEvictionRunsMillis: 60000
    #        minEvictableIdleTimeMillis: 300000
    #        validationQuery: select 'x'
    #        testWhileIdle: true
    #        testOnBorrow: false
    #        testOnReturn: false
    #        poolPreparedStatements: true
    #        maxOpenPreparedStatements: 20
    #  redis:
    ##??
    #    host: 192.168.1.203
    #    port: 6379
    ##
    ##??
    #    cluster:
    #      nodes:
    #      - 172.21.0.211:7000
    #      - 172.21.0.211:7001
    #      - 172.21.0.211:7002
    #      - 172.21.0.211:7003
    #      - 172.21.0.211:7004
    ##??
    #    sentinel:
    #      master: mymaster
    #      nodes:
    #      - 172.21.0.211:7005
    #      - 172.21.0.211:7006
    #      - 172.21.0.211:7007
    ##
    #    jedis:
    #      pool:
    ### ????????????????????
    #        max-active: 9
    ### ???????????????????????
    #        max-wait: -1
    ### ???????????
    #        max-idle: 9
    ### ???????????
    #        min-idle: 0
    ### Redis?????(???0)
    #    database: 0
    ### ??????????
    #    timeout: 60000


mybatis:
  mapper-locations: classpath:src/main/java/com/example/gitstudy/dao/*.xml #???mapper?????
  #type-aliases-package: com.mydream.backstate.*.entity #????????
web:
  export:
    path: E:/doc_f/
#file.save.upload.username
#file:
#  save:
#    path: /home/jk/tomcat-hn/webapps/hnsight-export/WEB-INF/saveFile/

file:
  save:
    path: /home/jkyw/web
    upload:
      username: jkyw
      password: zaq1XSW@
      privateKey:
      host: 10.218.94.141
      port: 22
equip:
  host:
    ip: 192.168.175.11111
#10.89.133.109
#sms.enable.kcOrderUrgeEnable
sms:
  url: http://10.218.94.139:9010/sms-service/rest/sms/login/sendMsg
  enable:
    kcOrderUrgeEnable: true
    ktOrderUrgeEnable: true
    tsOrderUrgeEnable: true
    gzOrderUrgeEnable: true
    yjoneOrderUrgeEnable: false
    csoneOrderUrgeEnable: false
feign:
  sys:
    getLoginUser: http://10.218.95.86:9080
eoms:
  url:
    faultSend: http://10.87.61.48/uip/services/EOMSProcessSheet?wsdl
